### ISSUE TITLE
feat(ticket-labels): add intelligent labels to tickets

### ISSUE THREAD

**Issue by kdev** [LEDBrain/Community-Service#97]
**Is your feature request related to a problem? Please describe.**
--

**Describe the solution you'd like**
```[tasklist]
### Tasks
- [ ] admin/mod can create a label-content pair (command)
- [ ] create a NLU/NLP model for the server based on that info
- [ ] add labels to tickets based on that model
``` 

**Describe alternatives you've considered**
No ticket system, this may be discussed

**Additional context**
-- none --
